export enum VisaDetailCategory {
  JobVisa,
  Education,
  Residence,
  Travel,
  Etc,
}

export enum PreferredVisa {
  StudentVisa,
  JobSeekingVisa,
  EmploymentVisa,
  Residence,
  OverseasKorean,
  PermanentResidence,
  InternationalMarriage,
}

export enum VisaCode {
  NA = 'N/A',
  C4 = 'c-4',
  D10 = 'd-10',
  E1 = 'e-1',
  E2 = 'e-2',
  E3 = 'e-3',
  E4 = 'e-4',
  E5 = 'e-5',
  E6 = 'e-6',
  E7 = 'e-7',
  E8 = 'e-8',
  E9 = 'e-9',
  E10 = 'e-10',
  H1 = 'h-1',
  H2 = 'h-2',
  D2 = 'd-2',
  D4 = 'd-4',
  F1 = 'f-1',
  F2 = 'f-2',
  F3 = 'f-3',
  F4 = 'f-4',
  F5 = 'f-5',
  F6 = 'f-6',
  B1 = 'b-1',
  B2 = 'b-2',
  C3 = 'c-3',
  A1 = 'a-1',
  C1 = 'c-1',
  D1 = 'd-1',
  D3 = 'd-3',
  D5 = 'd-5',
  D7 = 'd-7',
  D8 = 'd-8',
  D9 = 'd-9',
  G1 = 'g-1',
  A2 = 'a-2',
  A3 = 'a-3',
  D6 = 'd-6',
}

export const VisaStatus: Record<VisaCode, string> = {
  [VisaCode.NA]: 'N/A(비자없음)',
  [VisaCode.A1]: '외교(A-1)',
  [VisaCode.A2]: '공무(A-1)',
  [VisaCode.A3]: '협정(A-3)',
  [VisaCode.B1]: '사증면제(B-1)',
  [VisaCode.B2]: '관광통과(B-2)',
  [VisaCode.C1]: '일시취재(C-1)',
  [VisaCode.C3]: '단기방문(C-3)',
  [VisaCode.C4]: '외교(C-4)',
  [VisaCode.D1]: '문화예술(D-1)',
  [VisaCode.D2]: '유학(D-2)',
  [VisaCode.D3]: '기술연수(D-3)',
  [VisaCode.D4]: '일반연수(D-4)',
  [VisaCode.D5]: '취재(D-5)',
  [VisaCode.D6]: '종교(D-6)',
  [VisaCode.D7]: '주재(D-7)',
  [VisaCode.D8]: '기업투자(D-8)',
  [VisaCode.D9]: '무역경영(D-9)',
  [VisaCode.D10]: '구직(D-10)',
  [VisaCode.E1]: '교수(E-1)',
  [VisaCode.E2]: '회화지도(E-2)',
  [VisaCode.E3]: '연구(E-3)',
  [VisaCode.E4]: '기술지도(E-4)',
  [VisaCode.E5]: '전문직업(E-5)',
  [VisaCode.E6]: '예술흥행(E-6)',
  [VisaCode.E7]: '특정활동(E-7)',
  [VisaCode.E8]: '계절근로(E-8)',
  [VisaCode.E9]: '비전문취업(E-9)',
  [VisaCode.E10]: '선원취업(E-10)',
  [VisaCode.F1]: '방문동거(F-1)',
  [VisaCode.F2]: '거주(F-2)',
  [VisaCode.F3]: '동반(F-3)',
  [VisaCode.F4]: '재외동포(F-4)',
  [VisaCode.F5]: '영주(F-5)',
  [VisaCode.F6]: '결혼이민(F-6)',
  [VisaCode.G1]: '기타(G-1)',
  [VisaCode.H1]: '관광취업(H-1)',
  [VisaCode.H2]: '방문취업(H-2)',
};

const jobVisa = {
  C4: {
    type: 'C-4',
    title: '단기취업',
    description: [
      '법무부장관이 관계 중앙행정기관의 장과 협의하여 정하는 농작물 재배 수확 및 수산물 원시가공 분야에서 취업활동을 하려는 사람으로서 법무부장관이 인정하는 사람 (C-4-1~4)',
      '일시흥행, 광고․패션모델, 강의․강연, 연구, 기술지도 등 수익을 목적으로 단기간 취업활동을 하려는 자(C-4-5)',
      '1회에 부여할 수 있는 체류기간 상한 90일',
    ],
    subject: ['계절근로 단기취업(C-4-1, C-4-2, C-4-3, C-4-4)', ''],
  },
};
